In [1]:
import numpy as np

# Compute stats

In [2]:
arr = np.array(np.arange(20))

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
mean_array = np.nanmean(arr)

In [9]:
mean_array

9.5

In [10]:
std_array = np.nanstd(arr)

In [11]:
std_array

5.766281297335398

In [12]:
var_array = np.nanvar(arr)

In [13]:
var_array

33.25

# Sorting of Arrays

In [15]:
array2 = np.array([122,35,0,75,94])
np.sort(array2)

array([  0,  35,  75,  94, 122])

In [16]:
np.sort(array2)[::-1]

array([122,  94,  75,  35,   0])

# Filter Arrays

In [17]:
filtered = arr[arr > 4]

In [18]:
filtered

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Save Read Data

In [29]:
np.savez("testsave", filtered = filtered, array2 = array2)

In [30]:
loaded = np.load("./testsave.npz")

In [31]:
future_loaded = loaded["filtered"]

In [32]:
future_loaded

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
future_loaded2 = loaded["array2"]

In [35]:
future_loaded2

array([122,  35,   0,  75,  94])